export const categories = [
  { id: "puja-samagri", name: "पूजा सामग्री", nameEn: "Puja Samagri" },
  { id: "hawan-samagri", name: "हवन सामग्री", nameEn: "Hawan Samagri" },
  { id: "incense", name: "धूप-अगरबत्ती", nameEn: "Incense" },
  { id: "flowers", name: "फूल-माला", nameEn: "Flowers & Garlands" },
  { id: "oils", name: "तेल-घी", nameEn: "Oils & Ghee" },
  { id: "sweets", name: "प्रसाद-मिठाई", nameEn: "Prasad & Sweets" },
]

export const products = [
  {
    id: 1,
    slug: "sampurn-durga-puja-samagri-pack-ranchi",
    name: "संपूर्ण दुर्गा पूजा सामग्री पैक",
    nameEn: "Complete Durga Puja Samagri Pack",
    category: "puja-samagri",
    price: 599,
    originalPrice: 799,
    image: "/complete-puja-samagri-set-with-kalash-diya-incense.jpg",
    description:
      "दुर्गा पूजा के लिए संपूर्ण सामग्री का विशेष पैक। इसमें कलश, दीया, अगरबत्ती, रोली, चावल, फूल, प्रसाद, और माता दुर्गा की पूजा के लिए आवश्यक सभी 21 सामग्री शामिल है। रांची में सबसे लोकप्रिय दुर्गा पूजा पैक।",
    features: [
      "21 आवश्यक पूजा सामग्री",
      "कलश, दीया, और आरती थाली",
      "अगरबत्ती, धूप, और कपूर",
      "रोली, चावल, और हल्दी",
      "फूल, माला, और चुनरी",
      "प्रसाद और मिठाई",
      "दुर्गा माता की तस्वीर",
      "पूजा विधि गाइड शामिल",
    ],
    contents: [
      "पीतल का कलश - 1 पीस",
      "मिट्टी के दीये - 11 पीस",
      "अगरबत्ती - 2 पैकेट",
      "धूप बत्ती - 1 पैकेट",
      "कपूर - 50 ग्राम",
      "रोली - 100 ग्राम",
      "चावल - 250 ग्राम",
      "हल्दी पाउडर - 50 ग्राम",
      "चंदन पाउडर - 25 ग्राम",
      "गुड़ - 100 ग्राम",
      "सुपारी - 11 पीस",
      "नारियल - 1 पीस",
      "केला - 5 पीस",
      "फूल (गेंदा, गुलाब) - 2 किलो",
      "आम के पत्ते - 1 गुच्छा",
      "तुलसी के पत्ते - 1 गुच्छा",
      "माला (फूलों की) - 2 पीस",
      "लाल चुनरी - 1 पीस",
      "कलावा (मौली) - 1 रोल",
      "आरती की थाली - 1 पीस",
      "दुर्गा माता की तस्वीर - 1 पीस",
    ],
    inStock: true,
    rating: 4.9,
    reviewCount: 287,
    orderCount: 142,
    reviews: [
      {
        id: 1,
        name: "प्रिया शर्मा",
        rating: 5,
        comment: "बहुत ही बेहतरीन पैक है। दुर्गा पूजा के लिए सब कुछ मिल गया। रांची में इससे अच्छा पैक कहीं नहीं मिलता।",
        date: "2024-10-15",
        verified: true,
      },
      {
        id: 2,
        name: "राजेश कुमार",
        rating: 5,
        comment: "माँ सिद्धि से हमेशा सामान लेते हैं। क्वालिटी बहुत अच्छी है और सब कुछ फ्रेश मिलता है।",
        date: "2024-10-12",
        verified: true,
      },
      {
        id: 3,
        name: "सुनीता देवी",
        rating: 4,
        comment: "अच्छा पैक है। सभी सामान अच्छी क्वालिटी का है। डिलीवरी भी टाइम पर हुई।",
        date: "2024-10-08",
        verified: true,
      },
    ],
  },
  {
    id: 2,
    slug: "sampurn-puja-samagri-set-ranchi",
    name: "संपूर्ण पूजा सामग्री सेट",
    nameEn: "Complete Puja Samagri Set",
    category: "puja-samagri",
    price: 299,
    originalPrice: 399,
    image: "/complete-puja-samagri-set-with-kalash-diya-incense.jpg",
    description:
      "पूर्ण पूजा के लिए आवश्यक सभी सामग्री का संपूर्ण सेट। इसमें कलश, दीया, अगरबत्ती, रोली, चावल, और अन्य पूजा सामग्री शामिल है।",
    features: ["कलश और दीया", "अगरबत्ती और धूप", "रोली और चावल", "कपूर और तिलक"],
    inStock: true,
    rating: 4.8,
    reviewCount: 156,
    orderCount: 89,
    reviews: [
      {
        id: 1,
        name: "अनिता सिंह",
        rating: 5,
        comment: "बहुत अच्छा सेट है। सभी चीजें अच्छी क्वालिटी की हैं।",
        date: "2024-10-10",
        verified: true,
      },
    ],
  },
  {
    id: 3,
    slug: "hawan-samagri-500g-ranchi",
    name: "हवन सामग्री (500 ग्राम)",
    nameEn: "Hawan Samagri (500g)",
    category: "hawan-samagri",
    price: 149,
    originalPrice: 199,
    image: "/hawan-samagri-mixed-herbs-for-fire-ritual.jpg",
    description:
      "शुद्ध और प्राकृतिक हवन सामग्री जो हवन कुंड में डालने के लिए तैयार है। इसमें सभी आवश्यक जड़ी-बूटियां और सुगंधित द्रव्य शामिल हैं।",
    features: ["500 ग्राम पैकेट", "शुद्ध प्राकृतिक सामग्री", "सुगंधित जड़ी-बूटी", "हवन के लिए तैयार"],
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    orderCount: 67,
    reviews: [
      {
        id: 1,
        name: "मनोज पांडे",
        rating: 5,
        comment: "हवन सामग्री बहुत अच्छी है। सुगंध भी बहुत अच्छी आती है।",
        date: "2024-10-05",
        verified: true,
      },
    ],
  },
  {
    id: 4,
    slug: "gangajal-holy-water-ranchi",
    name: "गंगाजल (पवित्र जल)",
    nameEn: "Gangajal (Holy Water)",
    category: "puja-samagri",
    price: 99,
    originalPrice: 129,
    image: "/gangajal-holy-water-bottle-for-puja.jpg",
    description: "हरिद्वार से लाया गया शुद्ध गंगाजल। सभी धार्मिक अनुष्ठानों और पूजा के लिए आवश्यक पवित्र जल।",
    features: ["हरिद्वार से शुद्ध गंगाजल", "250ml बोतल", "सील पैक", "पूजा के लिए आवश्यक"],
    inStock: true,
    rating: 4.9,
    reviewCount: 234,
    orderCount: 156,
    reviews: [
      {
        id: 1,
        name: "गीता देवी",
        rating: 5,
        comment: "बिल्कुल शुद्ध गंगाजल है। पैकिंग भी अच्छी है।",
        date: "2024-10-14",
        verified: true,
      },
    ],
  },
  {
    id: 5,
    slug: "sandalwood-powder-chandan-ranchi",
    name: "चंदन पाउडर (100 ग्राम)",
    nameEn: "Sandalwood Powder (100g)",
    category: "puja-samagri",
    price: 199,
    originalPrice: 249,
    image: "/sandalwood-powder-chandan-for-tilaka.jpg",
    description: "शुद्ध चंदन का बारीक पाउडर। तिलक लगाने और पूजा में उपयोग के लिए उत्तम गुणवत्ता का चंदन।",
    features: ["100% शुद्ध चंदन", "100 ग्राम पैकेट", "बारीक पाउडर", "सुगंधित और शीतल"],
    inStock: true,
    rating: 4.6,
    reviewCount: 67,
    orderCount: 45,
    reviews: [
      {
        id: 1,
        name: "रमेश गुप्ता",
        rating: 4,
        comment: "चंदन की क्वालिटी अच्छी है। सुगंध भी बहुत अच्छी है।",
        date: "2024-10-01",
        verified: true,
      },
    ],
  },
  {
    id: 6,
    slug: "clay-diya-set-12-pieces-ranchi",
    name: "दीया सेट (12 पीस)",
    nameEn: "Diya Set (12 Pieces)",
    category: "puja-samagri",
    price: 79,
    originalPrice: 99,
    image: "/clay-diyas-oil-lamps-set-for-diwali-puja.jpg",
    description: "मिट्टी के पारंपरिक दीये का सेट। दीवाली, पूजा और अन्य त्योहारों के लिए आदर्श।",
    features: ["12 दीयों का सेट", "मिट्टी के पारंपरिक दीये", "त्योहारों के लिए उत्तम", "हस्तनिर्मित"],
    inStock: true,
    rating: 4.5,
    reviewCount: 123,
    orderCount: 98,
    reviews: [
      {
        id: 1,
        name: "सुमित्रा यादव",
        rating: 5,
        comment: "दीये बहुत अच्छे हैं। दीवाली में बहुत काम आए।",
        date: "2024-09-28",
        verified: true,
      },
    ],
  },
  {
    id: 7,
    slug: "pure-camphor-kapur-ranchi",
    name: "कपूर (50 ग्राम)",
    nameEn: "Camphor (50g)",
    category: "puja-samagri",
    price: 59,
    originalPrice: 79,
    image: "/camphor-kapur-tablets-for-aarti.jpg",
    description: "शुद्ध कपूर की गोलियां। आरती और पूजा के लिए आवश्यक सुगंधित कपूर।",
    features: ["50 ग्राम पैकेट", "शुद्ध कपूर", "आरती के लिए उत्तम", "लंबे समय तक जलता है"],
    inStock: true,
    rating: 4.7,
    reviewCount: 98,
    orderCount: 76,
    reviews: [
      {
        id: 1,
        name: "विनोद कुमार",
        rating: 5,
        comment: "कपूर बहुत अच्छा है। आरती में बहुत अच्छी सुगंध आती है।",
        date: "2024-09-25",
        verified: true,
      },
    ],
  },
  {
    id: 8,
    slug: "brass-kalash-water-pot-ranchi",
    name: "पीतल का कलश",
    nameEn: "Brass Kalash (Water Pot)",
    category: "puja-samagri",
    price: 399,
    originalPrice: 499,
    image: "/brass-kalash-water-pot-puja.jpg",
    description: "शुद्ध पीतल का बना पारंपरिक कलश। सभी पूजा-पाठ और धार्मिक अनुष्ठानों के लिए आवश्यक।",
    features: ["शुद्ध पीतल निर्मित", "पारंपरिक डिजाइन", "मध्यम साइज", "लंबे समय तक चलने वाला"],
    inStock: true,
    rating: 4.8,
    reviewCount: 145,
    orderCount: 89,
    reviews: [],
  },
  {
    id: 9,
    slug: "roli-chawal-tilak-set-ranchi",
    name: "रोली चावल तिलक सेट",
    nameEn: "Roli Chawal Tilak Set",
    category: "puja-samagri",
    price: 89,
    originalPrice: 119,
    image: "/roli-chawal-tilak-set-puja.jpg",
    description: "पूजा के लिए आवश्यक रोली, चावल और तिलक का संपूर्ण सेट।",
    features: ["रोली 100 ग्राम", "चावल 250 ग्राम", "तिलक पाउडर", "प्लास्टिक कंटेनर"],
    inStock: true,
    rating: 4.6,
    reviewCount: 78,
    orderCount: 56,
    reviews: [],
  },
  {
    id: 10,
    slug: "puja-thali-brass-set-ranchi",
    name: "पूजा थाली सेट",
    nameEn: "Puja Thali Brass Set",
    category: "puja-samagri",
    price: 299,
    originalPrice: 399,
    image: "/brass-puja-thali-set-aarti.jpg",
    description: "पीतल की सुंदर पूजा थाली जिसमें सभी आवश्यक कटोरियां और दीया शामिल है।",
    features: ["पीतल की थाली", "5 छोटी कटोरियां", "1 दीया", "हस्तनिर्मित डिजाइन"],
    inStock: true,
    rating: 4.7,
    reviewCount: 92,
    orderCount: 67,
    reviews: [],
  },
  {
    id: 11,
    slug: "rudraksha-mala-108-beads-ranchi",
    name: "रुद्राक्ष माला (108 दाने)",
    nameEn: "Rudraksha Mala (108 Beads)",
    category: "puja-samagri",
    price: 199,
    originalPrice: 299,
    image: "/rudraksha-mala-108-beads-prayer.jpg",
    description: "प्राकृतिक रुद्राक्ष की 108 दानों वाली माला। जप और ध्यान के लिए उत्तम।",
    features: ["108 प्राकृतिक रुद्राक्ष", "मजबूत धागा", "जप के लिए आदर्श", "आध्यात्मिक लाभ"],
    inStock: true,
    rating: 4.9,
    reviewCount: 156,
    orderCount: 123,
    reviews: [],
  },
  {
    id: 12,
    slug: "tulsi-mala-prayer-beads-ranchi",
    name: "तुलसी माला",
    nameEn: "Tulsi Mala Prayer Beads",
    category: "puja-samagri",
    price: 79,
    originalPrice: 99,
    image: "/tulsi-mala-prayer-beads-krishna.jpg",
    description: "पवित्र तुलसी की लकड़ी से बनी माला। भगवान कृष्ण की पूजा के लिए विशेष।",
    features: ["तुलसी की लकड़ी", "108 दाने", "कृष्ण भक्ति के लिए", "हल्की और टिकाऊ"],
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
    orderCount: 67,
    reviews: [],
  },
  {
    id: 13,
    slug: "hawan-kund-copper-medium-ranchi",
    name: "हवन कुंड (तांबा)",
    nameEn: "Hawan Kund Copper Medium",
    category: "hawan-samagri",
    price: 799,
    originalPrice: 999,
    image: "/copper-hawan-kund-fire-ritual.jpg",
    description: "तांबे का बना मध्यम साइज का हवन कुंड। घर में हवन करने के लिए आदर्श।",
    features: ["शुद्ध तांबा निर्मित", "मध्यम साइज", "घर के लिए उपयुक्त", "लंबे समय तक चलने वाला"],
    inStock: true,
    rating: 4.8,
    reviewCount: 67,
    orderCount: 34,
    reviews: [],
  },
  {
    id: 14,
    slug: "hawan-samagri-1kg-premium-ranchi",
    name: "हवन सामग्री (1 किलो) प्रीमियम",
    nameEn: "Premium Hawan Samagri (1kg)",
    category: "hawan-samagri",
    price: 249,
    originalPrice: 329,
    image: "/premium-hawan-samagri-1kg-herbs.jpg",
    description: "प्रीमियम क्वालिटी की हवन सामग्री। विशेष जड़ी-बूटियों का मिश्रण।",
    features: ["1 किलो पैकेट", "प्रीमियम क्वालिटी", "विशेष जड़ी-बूटी", "सुगंधित मिश्रण"],
    inStock: true,
    rating: 4.9,
    reviewCount: 123,
    orderCount: 89,
    reviews: [],
  },
  {
    id: 15,
    slug: "ghee-for-hawan-500ml-ranchi",
    name: "हवन के लिए घी (500ml)",
    nameEn: "Ghee for Hawan (500ml)",
    category: "hawan-samagri",
    price: 299,
    originalPrice: 399,
    image: "/pure-ghee-hawan-500ml-bottle.jpg",
    description: "शुद्ध गाय का घी हवन के लिए विशेष रूप से तैयार।",
    features: ["शुद्ध गाय का घी", "500ml बोतल", "हवन के लिए विशेष", "सील पैक"],
    inStock: true,
    rating: 4.7,
    reviewCount: 78,
    orderCount: 56,
    reviews: [],
  },
  {
    id: 16,
    slug: "mango-wood-hawan-samidha-ranchi",
    name: "आम की लकड़ी समिधा",
    nameEn: "Mango Wood Hawan Samidha",
    category: "hawan-samagri",
    price: 149,
    originalPrice: 199,
    image: "/mango-wood-samidha-hawan-sticks.jpg",
    description: "आम की शुद्ध लकड़ी की समिधा। हवन के लिए पारंपरिक और शुभ।",
    features: ["आम की लकड़ी", "1 किलो पैकेट", "सूखी और तैयार", "पारंपरिक समिधा"],
    inStock: true,
    rating: 4.6,
    reviewCount: 45,
    orderCount: 32,
    reviews: [],
  },
  {
    id: 17,
    slug: "sandalwood-incense-sticks-ranchi",
    name: "चंदन अगरबत्ती",
    nameEn: "Sandalwood Incense Sticks",
    category: "incense",
    price: 89,
    originalPrice: 119,
    image: "/sandalwood-incense-sticks-chandan.jpg",
    description: "प्राकृतिक चंदन की सुगंध वाली अगरबत्ती। ध्यान और पूजा के लिए उत्तम।",
    features: ["चंदन की सुगंध", "20 अगरबत्ती", "लंबे समय तक जलती है", "प्राकृतिक सामग्री"],
    inStock: true,
    rating: 4.8,
    reviewCount: 234,
    orderCount: 189,
    reviews: [],
  },
  {
    id: 18,
    slug: "jasmine-incense-sticks-ranchi",
    name: "चमेली अगरबत्ती",
    nameEn: "Jasmine Incense Sticks",
    category: "incense",
    price: 69,
    originalPrice: 89,
    image: "/jasmine-incense-sticks-chameli.jpg",
    description: "चमेली के फूल की मनमोहक सुगंध वाली अगरबत्ती।",
    features: ["चमेली की सुगंध", "20 अगरबत्ती", "मनमोहक खुशबू", "शाम की पूजा के लिए"],
    inStock: true,
    rating: 4.6,
    reviewCount: 167,
    orderCount: 134,
    reviews: [],
  },
  {
    id: 19,
    slug: "rose-incense-sticks-ranchi",
    name: "गुलाब अगरबत्ती",
    nameEn: "Rose Incense Sticks",
    category: "incense",
    price: 79,
    originalPrice: 99,
    image: "/rose-incense-sticks-gulab.jpg",
    description: "गुलाब की मधुर सुगंध वाली अगरबत्ती। प्रेम और भक्ति के लिए।",
    features: ["गुलाब की सुगंध", "20 अगरबत्ती", "मधुर खुशबू", "भक्ति के लिए उत्तम"],
    inStock: true,
    rating: 4.7,
    reviewCount: 145,
    orderCount: 112,
    reviews: [],
  },
  {
    id: 20,
    slug: "dhoop-batti-cone-incense-ranchi",
    name: "धूप बत्ती (कोन)",
    nameEn: "Dhoop Batti Cone Incense",
    category: "incense",
    price: 59,
    originalPrice: 79,
    image: "/dhoop-batti-cone-incense-traditional.jpg",
    description: "पारंपरिक धूप बत्ती कोन। तेज सुगंध और लंबे समय तक जलने वाली।",
    features: ["12 धूप कोन", "तेज सुगंध", "लंबे समय तक जलती", "पारंपरिक फॉर्मूला"],
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
    orderCount: 67,
    reviews: [],
  },
  {
    id: 21,
    slug: "marigold-flowers-fresh-ranchi",
    name: "गेंदे के फूल (ताजे)",
    nameEn: "Fresh Marigold Flowers",
    category: "flowers",
    price: 49,
    originalPrice: 69,
    image: "/fresh-marigold-flowers-genda.jpg",
    description: "ताजे गेंदे के फूल। पूजा और सजावट के लिए आदर्श।",
    features: ["ताजे गेंदे के फूल", "500 ग्राम", "पूजा के लिए उत्तम", "दैनिक आपूर्ति"],
    inStock: true,
    rating: 4.4,
    reviewCount: 156,
    orderCount: 234,
    reviews: [],
  },
  {
    id: 22,
    slug: "rose-flowers-fresh-red-ranchi",
    name: "लाल गुलाब के फूल",
    nameEn: "Fresh Red Rose Flowers",
    category: "flowers",
    price: 79,
    originalPrice: 99,
    image: "/fresh-red-rose-flowers-puja.jpg",
    description: "ताजे लाल गुलाब के फूल। देवी-देवताओं की पूजा के लिए विशेष।",
    features: ["ताजे लाल गुलाब", "25 फूल", "देवी पूजा के लिए", "सुगंधित"],
    inStock: true,
    rating: 4.6,
    reviewCount: 123,
    orderCount: 189,
    reviews: [],
  },
  {
    id: 23,
    slug: "lotus-flowers-artificial-ranchi",
    name: "कमल के फूल (कृत्रिम)",
    nameEn: "Artificial Lotus Flowers",
    category: "flowers",
    price: 199,
    originalPrice: 249,
    image: "/artificial-lotus-flowers-kamal.jpg",
    description: "सुंदर कृत्रिम कमल के फूल। लक्ष्मी पूजा के लिए विशेष।",
    features: ["कृत्रिम कमल", "5 फूल सेट", "लक्ष्मी पूजा के लिए", "लंबे समय तक चलने वाले"],
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    orderCount: 67,
    reviews: [],
  },
  {
    id: 24,
    slug: "flower-garland-mixed-ranchi",
    name: "मिश्रित फूलों की माला",
    nameEn: "Mixed Flower Garland",
    category: "flowers",
    price: 129,
    originalPrice: 159,
    image: "/mixed-flower-garland-mala.jpg",
    description: "गेंदा, गुलाब और अन्य फूलों की सुंदर माला। मूर्ति सजाने के लिए।",
    features: ["मिश्रित फूलों की माला", "2 फीट लंबी", "ताजे फूल", "मूर्ति सजाने के लिए"],
    inStock: true,
    rating: 4.5,
    reviewCount: 78,
    orderCount: 56,
    reviews: [],
  },
  {
    id: 25,
    slug: "mustard-oil-puja-500ml-ranchi",
    name: "सरसों का तेल (पूजा के लिए)",
    nameEn: "Mustard Oil for Puja (500ml)",
    category: "oils",
    price: 149,
    originalPrice: 179,
    image: "/mustard-oil-puja-500ml-bottle.jpg",
    description: "शुद्ध सरसों का तेल। दीया जलाने और पूजा के लिए विशेष।",
    features: ["शुद्ध सरसों का तेल", "500ml बोतल", "दीया के लिए उत्तम", "लंबे समय तक जलता है"],
    inStock: true,
    rating: 4.6,
    reviewCount: 134,
    orderCount: 98,
    reviews: [],
  },
  {
    id: 26,
    slug: "sesame-oil-til-puja-ranchi",
    name: "तिल का तेल (पूजा)",
    nameEn: "Sesame Oil for Puja",
    category: "oils",
    price: 179,
    originalPrice: 219,
    image: "/sesame-oil-til-puja-bottle.jpg",
    description: "शुद्ध तिल का तेल। शनि पूजा और विशेष अनुष्ठानों के लिए।",
    features: ["शुद्ध तिल का तेल", "250ml बोतल", "शनि पूजा के लिए", "पारंपरिक तेल"],
    inStock: true,
    rating: 4.7,
    reviewCount: 89,
    orderCount: 67,
    reviews: [],
  },
  {
    id: 27,
    slug: "coconut-oil-pure-puja-ranchi",
    name: "नारियल तेल (शुद्ध)",
    nameEn: "Pure Coconut Oil",
    category: "oils",
    price: 199,
    originalPrice: 249,
    image: "/pure-coconut-oil-puja-bottle.jpg",
    description: "शुद्ध नारियल का तेल। दक्षिण भारतीय पूजा पद्धति के लिए।",
    features: ["शुद्ध नारियल तेल", "500ml कंटेनर", "दक्षिण भारतीय पूजा", "प्राकृतिक और शुद्ध"],
    inStock: true,
    rating: 4.8,
    reviewCount: 156,
    orderCount: 123,
    reviews: [],
  },
  {
    id: 28,
    slug: "cow-ghee-pure-1kg-ranchi",
    name: "गाय का घी (1 किलो)",
    nameEn: "Pure Cow Ghee (1kg)",
    category: "oils",
    price: 899,
    originalPrice: 1099,
    image: "/pure-cow-ghee-1kg-container.jpg",
    description: "शुद्ध गाय का घी। पूजा, हवन और प्रसाद बनाने के लिए।",
    features: ["100% शुद्ध गाय का घी", "1 किलो कंटेनर", "पूजा और हवन के लिए", "प्रीमियम क्वालिटी"],
    inStock: true,
    rating: 4.9,
    reviewCount: 234,
    orderCount: 167,
    reviews: [],
  },
  {
    id: 29,
    slug: "laddu-prasad-500g-ranchi",
    name: "लड्डू प्रसाद (500 ग्राम)",
    nameEn: "Laddu Prasad (500g)",
    category: "sweets",
    price: 199,
    originalPrice: 249,
    image: "/laddu-prasad-500g-box.jpg",
    description: "ताजे बने लड्डू। गणेश जी और अन्य देवताओं के लिए प्रसाद।",
    features: ["ताजे बने लड्डू", "500 ग्राम बॉक्स", "गणेश जी के लिए", "स्वादिष्ट प्रसाद"],
    inStock: true,
    rating: 4.7,
    reviewCount: 189,
    orderCount: 145,
    reviews: [],
  },
  {
    id: 30,
    slug: "kheer-prasad-ready-ranchi",
    name: "खीर प्रसाद (तैयार)",
    nameEn: "Ready Kheer Prasad",
    category: "sweets",
    price: 149,
    originalPrice: 189,
    image: "/kheer-prasad-ready-container.jpg",
    description: "तैयार खीर प्रसाद। कृष्ण जी और अन्य देवताओं के लिए।",
    features: ["तैयार खीर", "500ml कंटेनर", "कृष्ण जी के लिए", "मिठास भरपूर"],
    inStock: true,
    rating: 4.6,
    reviewCount: 123,
    orderCount: 89,
    reviews: [],
  },
  {
    id: 31,
    slug: "peda-prasad-250g-ranchi",
    name: "पेड़ा प्रसाद (250 ग्राम)",
    nameEn: "Peda Prasad (250g)",
    category: "sweets",
    price: 179,
    originalPrice: 219,
    image: "/peda-prasad-250g-box.jpg",
    description: "मिठाई की दुकान से ताजे पेड़े। सभी देवताओं के लिए उत्तम प्रसाद।",
    features: ["ताजे पेड़े", "250 ग्राम बॉक्स", "सभी देवताओं के लिए", "पारंपरिक स्वाद"],
    inStock: true,
    rating: 4.8,
    reviewCount: 167,
    orderCount: 134,
    reviews: [],
  },
  {
    id: 32,
    slug: "dry-fruits-mixed-prasad-ranchi",
    name: "मिश्रित ड्राई फ्रूट्स प्रसाद",
    nameEn: "Mixed Dry Fruits Prasad",
    category: "sweets",
    price: 299,
    originalPrice: 399,
    image: "/mixed-dry-fruits-prasad-box.jpg",
    description: "बादाम, काजू, किशमिश का मिश्रण। प्रीमियम प्रसाद के लिए।",
    features: ["बादाम, काजू, किशमिश", "250 ग्राम बॉक्स", "प्रीमियम प्रसाद", "पोषक तत्वों से भरपूर"],
    inStock: true,
    rating: 4.9,
    reviewCount: 145,
    orderCount: 112,
    reviews: [],
  },
]

export const getProductsByCategory = (categoryId) => {
  return products.filter((product) => product.category === categoryId)
}

export const getProductById = (id) => {
  return products.find((product) => product.id === Number.parseInt(id))
}

export const getFeaturedProducts = () => {
  return products.slice(0, 4)
}

export const getProductBySlug = (slug) => {
  return products.find((product) => product.slug === slug)
}

export const getRandomOrderCount = (min = 45, max = 150) => {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

export const getProductsForLocation = (location = "ranchi") => {
  return products.map((product) => ({
    ...product,
    locationKeywords: `${location} jharkhand puja samagri shop`,
  }))
}
